on: [workflow_dispatch]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout discord-gdextension
        uses: actions/checkout@v3
        with:
          path: "repo"
          submodules: recursive
      - name: Get Discord GameSDK and extract libs
        run: |
          curl https://dl-game-sdk.discordapp.net/2.5.6/discord_game_sdk.zip --output discord_game_sdk.zip
          7z x discord_game_sdk.zip -osdk
          chdir
          dir
          mkdir repo/addons/discord/bin
          cp sdk/lib/x64_86/* repo/addons/discord/bin/
      - name: Install Build Requirements
        run: |
          python --version
          python -m pip install scons
          scons --version
      - name: Build Windows
        run: |
          scons
      - name: Upload Windows Build
        uses: actions/upload-artifact@v3
        with:
          name: windows_64
          path: repo/addons/
          retention-days: 1