on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Options: template_debug | template_release'
        required: true
        default: 'template_debug'

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Get Discord GameSDK and extract libs
        run: |
          curl https://dl-game-sdk.discordapp.net/2.5.6/discord_game_sdk.zip --output discord_game_sdk.zip
          7z x discord_game_sdk.zip -odiscord_game_sdk
          mkdir addons/discord/bin
          robocopy discord_game_sdk/lib/x86_64 addons/discord/bin
          EXIT 0
      - name: Install Build Requirements
        run: |
          python --version
          python -m pip install scons
          scons --version
      - name: Build Windows
        run: |
          scons target=${{ inputs.target }}
      - name: Upload Windows Build
        uses: actions/upload-artifact@v3
        with:
          name: libgddiscord.windows.${{ inputs.target }}.x86_64.dll.zip
          path: addons/discord/bin/libgddiscord.windows.${{ inputs.target }}.x86_64.dll
          retention-days: 1