on: [workflow_dispatch]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Get Discord GameSDK and extract libs
        run: |
          dir
          curl https://dl-game-sdk.discordapp.net/2.5.6/discord_game_sdk.zip --output discord_game_sdk.zip
          dir
          7z x discord_game_sdk.zip -odiscord_game_sdk
          dir
          mkdir addons/discord/bin
          dir
          robocopy discord_game_sdk/lib/x86_64 addons/discord/bin
      - name: Install Build Requirements
        run: |
          python --version
          python -m pip install scons
          scons --version
      - name: Build Windows
        run: |
          scons
      - name: Upload Windows Build
        uses: actions/upload-artifact@v3
        with:
          name: windows_64
          path: addons/
          retention-days: 1